import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const ttFont = localFont({
  src: '/tt_norms_pro_serif_regular.ttf',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ttFont.className}>
        {children}
      </body>
    </html>
  );
}
